services:
  sgcc_electricity_app:
    build:
      context: .
      dockerfile: Dockerfile-for-github-action
    container_name: sgcc_electricity_arc
    env_file:
      - .env
    network_mode: host
    volumes:
      - /data:/data
    restart: unless-stopped
    init: true
